version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8080:8080'
    depends_on:
      - frontend
      - backend